#####################################################################
# Configuration base de données H2
#####################################################################
hibernate:
  driver-class-name:              org.h2.Driver
  url:                            jdbc:h2:mem:rentes-schema;;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS rentes

  username:                       sa
  password:
  dialect:                        org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto:                         create-drop
  show:
    sql:                          true


spring:
  h2:
    console:
      enabled:                    true
      path:                       /h2
