#####################################################################
# Configuration Spring de base
#####################################################################
# app name
spring:
  application:
    name:                            rentes-service
  #jackson null default desactivate
  jackson:
    default-property-inclusion:      NON_NULL
#profiles spring
  profiles:
    active:                          h2,maison

# mode jar, port et context
server:
  port:                              ${PORT:9020}
  servlet.context-path:                        /rentes-service
#####################################################################
# Configuration Spring actuator
#####################################################################
management:
  server.servlet.context-path:                         /actuator
  endpoints:
    web:
      exposure:
        include:

# configuration des endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    hypermedia:
      enabled:                            true
    actuator:
      enabled:                            true
    beans:
      enabled:                            true
    env:
      enabled:                            true
    metrics:
      enabled:                            true
    health:
      enabled:                            true
    mappings:
      enabled:                            true
    docs:
      enabled:                            true
    logfile:
      enabled:                            true
chaos:
  monkey:
    watcher:
      restController: true
    assaults:
      exceptions-active: true

elasticsearch:
  hosts:
    - http://localhost:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000